# Basic Python Programming
Description  : This script is going to show you how to learn Python from the beginning.
<br> Author  : Wilvan Dany Aritonang
<br> Date    : 30 September 2019
<br> Sources : [Google](www.google.com)

***

* Session 1 : Introduction
    * Arithmatics
    * Methods
    * Variables
    * Function
    * Loop
* Session 2 : Pandas and Numpy
    * Pandas
    * Numpy
* Session 3 : Data Cleansing
    * Drop Duplicates
    * Adding Missing Data

*Basic Python Programming*

**Basic Python Pragramming**

In [4]:
print ("Hellow World")

Hellow World

In [5]:
print (2+5)

7

![image 1](https://i.udemycdn.com/course/750x422/1817082_cf8a_9.jpg)

In [6]:
print (True)

True

In [7]:
print(type(True
          ))

<class 'bool'>

In [8]:
Fam = [2,3,4,5,6,7]
print (Fam)
type (Fam)

[2, 3, 4, 5, 6, 7]

list

In [14]:
animal = ['cat','dog','mokey']
for animal in animals:
          print(animal)
          nums = [0,1,2,3,4]
          squares = [x ** 2 for x in num]
        print(squares)

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 6)

In [20]:
a=10
b=20

if a == b:
print('yes')
else:
print('no')

IndentationError: expected an indented block (<ipython-input-20-802f01b42297>, line 5)

In [21]:
a=10
b=20
print(a)

10

In [22]:
a=10
b=20
if a == b:
print('yes')
else:
print('no')

IndentationError: expected an indented block (<ipython-input-22-00023269cd53>, line 4)

In [25]:
a=10
b=20

if a == b:
    print('yes')
else:
    print('no')

no

In [28]:
nums = [0,1,2,3,4]
squares = [x ** 2 for x in nums]
print(squares)

[0, 1, 4, 9, 16]

In [29]:
animal = ['cat','dog','mokey']
for animal in animals:
print(animal)

IndentationError: expected an indented block (<ipython-input-29-9bd1244ec8da>, line 3)

SyntaxError: EOL while scanning string literal (<ipython-input-30-5fd87a4f8fe5>, line 1)

In [31]:
pip3 install numpy
import numpy as np

SyntaxError: invalid syntax (<ipython-input-31-a370759bdff4>, line 1)

In [32]:
pip3 install numpy

SyntaxError: invalid syntax (<ipython-input-32-0a0fc7a77e37>, line 1)

In [34]:
!pip install numpy

Requirement already satisfied: numpy in c:\users\wilvanari\appdata\local\continuum\anaconda3\lib\site-packages (1.16.4)

In [35]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\wilvanari\appdata\local\continuum\anaconda3\lib\site-packages (0.24.2)
Requirement already satisfied: pytz>=2011k in c:\users\wilvanari\appdata\local\continuum\anaconda3\lib\site-packages (from pandas) (2019.1)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\users\wilvanari\appdata\local\continuum\anaconda3\lib\site-packages (from pandas) (2.8.0)
Requirement already satisfied: numpy>=1.12.0 in c:\users\wilvanari\appdata\local\continuum\anaconda3\lib\site-packages (from pandas) (1.16.4)
Requirement already satisfied: six>=1.5 in c:\users\wilvanari\appdata\local\continuum\anaconda3\lib\site-packages (from python-dateutil>=2.5.0->pandas) (1.12.0)

In [36]:
import numpy as np

In [37]:
import pandas as np

In [40]:
code = ['US', 'AUS', 'JPN', 'IN', 'RUS', 'MOR', 'EG']
names = ['United States', 'Australia', 'Japan', 'India',
'Russia','Morocco', 'Egypt']
dr = [True, False, False, False, True, True, True]
cpc = [809, 731, 588, 18, 200, 70, 45]

In [41]:
cars = pd.DataFrame(my_dict)

NameError: name 'pd' is not defined

In [42]:
import pandas as pd

In [43]:
cars = pd.DataFrame(my_dict)

NameError: name 'my_dict' is not defined

In [44]:
my_dict = {'ctrcode':code, 'country':names, 'drives_right':dr,
'cars_per_cap':cpc}

In [45]:
cars = pd.DataFrame(my_dict)

In [46]:
print(type(cars))

<class 'pandas.core.frame.DataFrame'>

In [47]:
print(cars)

  ctrcode        country  drives_right  cars_per_cap
0      US  United States          True           809
1     AUS      Australia         False           731
2     JPN          Japan         False           588
3      IN          India         False            18
4     RUS         Russia          True           200
5     MOR        Morocco          True            70
6      EG          Egypt          True            45

In [54]:
imdb = pd.read_csv('https://raw.githubusercontent.com/scalabretta/GroupProject--IMDB/master/Dataset/IMDB-database-update.csv', encoding='latin1')

In [56]:
imdb.shape

(3781, 36)

In [57]:
imdb.tail

<bound method NDFrame.tail of       movie_ID                                movie_title  duration  color  \
0            1                                     Avatar       178      1
1            2   Pirates of the Caribbean: At World's End       169      1
2            3                      The Dark Knight Rises       164      1
3            4                               Spider-Man 3       156      1
4            5         Batman v Superman: Dawn of Justice       183      1
5            6                           Superman Returns       169      1
6            7                               Man of Steel       143      1
7            8  The Hobbit: The Battle of the Five Armies       164      1
8            9                     The Amazing Spider-Man       153      1
9           10                                 Robin Hood       156      1
10          11                                  King Kong       201      1
11          12                                    Titanic       194      1
12          13                 Captain America: Civil War       147      1
13          14                                 Battleship       131      1
14          15                             Jurassic World       124      1
15          16                                    Skyfall       143      1
16          17                        Alice in Wonderland       108      1
17          18                      X-Men: The Last Stand       104      1
18          19                        Monsters University       104      1
19          20        Transformers: Revenge of the Fallen       150      1
20          21                   The Amazing Spider-Man 2       142      1
21          22                               TRON: Legacy       125      1
22          23                                     Cars 2       106      1
23          24                       Terminator Salvation       118      1
24          25                                  Furious 7       140      1
25          26                                World War Z       123      1
26          27                    Star Trek Into Darkness       132      1
27          28                                Pacific Rim       131      1
28          29                                      Brave        93      1
29          30                                     WALL-E        98      1
...        ...                                        ...       ...    ...
3751      3752                                 Soul Plane        92      1
3752      3753                             This Christmas       117      1
3753      3754                              5 Days of War       113      1
3754      3755                                  Sleepover        89      1
3755      3756                              Baggage Claim        96      1
3756      3757                               Best in Show        90      1
3757      3758                           The Players Club       104      1
3758      3759                             Little Fockers        98      1
3759      3760                               Delivery Man       105      1
3760      3761                 My Big Fat Greek Wedding 2        94      1
3761      3762                                   Top Five       102      1
3762      3763                                   Movie 43        94      1
3763      3764                             Get on the Bus       120      1
3764      3765                           The Longest Yard       113      1
3765      3766                          I Heart Huckabees       107      1
3766      3767                                 Epic Movie        93      1
3767      3768                  One Direction: This Is Us       106      1
3768      3769                           God's Not Dead 2       120      1
3769      3770                            Valentine's Day       125      1
3770      3771       What to Expect When You're Expecting       110      1
3771      3772                           Taking Woodstock       120      1
3772      3773                           Love the Coopers       107      1
3773      3774                           A Bridge Too Far       175      0
3774      3775                          The Expendables 3       131      1
3775      3776                       Cheaper by the Dozen        94      1
3776      3777                             New Year's Eve       113      1
3777      3778                              Boogie Nights       155      1
3778      3779                         Battle of the Year       110      1
3779      3780                                 The Master       144      1
3780      3781                         500 Days of Summer        95      1

      title_year      country language content_rating  budget_USD  gross_USD  \
0           2009          USA  English          PG-13   237000000  760505847
1           2007          USA  English          PG-13   300000000  309404152
2           2012          USA  English          PG-13   250000000  448130642
3           2007          USA  English          PG-13   258000000  336530303
4           2016          USA  English          PG-13   250000000  330249062
5           2006          USA  English          PG-13   209000000  200069408
6           2013          USA  English          PG-13   225000000  291021565
7           2014  New Zealand  English          PG-13   250000000  255108370
8           2012          USA  English          PG-13   230000000  262030663
9           2010          USA  English          PG-13   200000000  105219735
10          2005  New Zealand  English          PG-13   207000000  218051260
11          1997          USA  English          PG-13   200000000  658672302
12          2016          USA  English          PG-13   250000000  407197282
13          2012          USA  English          PG-13   209000000   65173160
14          2015          USA  English          PG-13   150000000  652177271
15          2012           UK  English          PG-13   200000000  304360277
16          2010          USA  English             PG   200000000  334185206
17          2006       Canada  English          PG-13   210000000  234360014
18          2013          USA  English              G   200000000  268488329
19          2009          USA  English          PG-13   200000000  402076689
20          2014          USA  English          PG-13   200000000  202853933
21          2010          USA  English             PG   170000000  172051787
22          2011          USA  English              G   200000000  191450875
23          2009          USA  English          PG-13   200000000  125320003
24          2015          USA  English          PG-13   190000000  350034110
25          2013          USA  English          PG-13   190000000  202351611
26          2013          USA  English          PG-13   190000000  228756232
27          2013          USA  English          PG-13   190000000  101785482
28          2012          USA  English             PG   185000000  237282182
29          2008          USA  English              G   180000000  223806889
...          ...          ...      ...            ...         ...        ...
3751        2004          USA  English              R    16000000   13922211
3752        2007          USA  English          PG-13    13000000   49121934
3753        2011      Georgia  English              R    20000000      17149
3754        2004          USA  English             PG    10000000    8070311
3755        2013          USA  English          PG-13     8500000   21564616
3756        2000          USA  English          PG-13     6000000   18621249
3757        1998          USA  English              R     4500000   23031390
3758        2010          USA  English          PG-13   100000000  148383780
3759        2013          USA  English          PG-13    26000000   30659817
3760        2016          USA  English          PG-13    18000000   59573085
3761        2014          USA  English              R    12000000   25277561
3762        2013          USA  English              R     6000000    8828771
3763        1996          USA  English              R     2400000    5731103
3764        2005          USA  English          PG-13    82000000  158115031
3765        2004          USA  English              R    22000000   12784713
3766        2007          USA  English          PG-13    20000000   39737645
3767        2013          USA  English             PG    10000000   28873374
3768        2016          USA  English             PG     5000000   20773070
3769        2010          USA  English          PG-13    52000000  110476776
3770        2012          USA  English          PG-13    40000000   41102171
3771        2009          USA  English              R    30000000    7443007
3772        2015          USA  English          PG-13    17000000   26284475
3773        1977          USA  English             PG    26000000   50800000
3774        2014          USA  English          PG-13    90000000   39292022
3775        2003          USA  English             PG    40000000  138614544
3776        2011          USA  English          PG-13    56000000   54540525
3777        1997          USA  English              R    15000000   26384919
3778        2013          USA  English          PG-13    20000000    8888355
3779        2012          USA  English              R    32000000   16377274
3780        2009          USA  English          PG-13     7500000   32391374

      ...  actor_3_facebook?  actor_3_facebook_likes  \
0     ...                  1                     855
1     ...                  1                    1000
2     ...                  1                   23000
3     ...                  1                    4000
4     ...                  1                    2000
5     ...                  1                     903
6     ...                  1                     748
7     ...                  1                     773
8     ...                  1                     963
9     ...                  1                     738
10    ...                  1                      84
11    ...                  1                     794
12    ...                  1                   11000
13    ...                  1                     627
14    ...                  1                    1000
15    ...                  1                     393
16    ...                  1                   11000
17    ...                  1                     560
18    ...                  1                     760
19    ...                  1                     464
20    ...                  1                     825
21    ...                  1                    1000
22    ...                  1                     776
23    ...                  1                     988
24    ...                  1                   14000
25    ...                  1                    1000
26    ...                  1                     928
27    ...                  1                     919
28    ...                  1                     838
29    ...                  1                     522
...   ...                ...                     ...
3751  ...                  1                     618
3752  ...                  1                     912
3753  ...                  1                      18
3754  ...                  1                    2000
3755  ...                  1                    1000
3756  ...                  1                     658
3757  ...                  1                     498
3758  ...                  1                     708
3759  ...                  1                     110
3760  ...                  1                     261
3761  ...                  1                     555
3762  ...                  1                    3000
3763  ...                  1                     702
3764  ...                  1                     421
3765  ...                  1                     678
3766  ...                  1                     729
3767  ...                  1                     547
3768  ...                  1                     295
3769  ...                  1                   11000
3770  ...                  1                     651
3771  ...                  1                     210
3772  ...                  1                      85
3773  ...                  1                      14
3774  ...                  1                   11000
3775  ...                  1                     597
3776  ...                  1                     307
3777  ...                  1                     170
3778  ...                  1                     826
3779  ...                  1                      15
3780  ...                  1                   11000

     cast_total_facebook_likes movie_facebook?  movie_facebook_likes;  \
0                         4834               1                  33000
1                        48350               0                      0
2                       106759               1                 164000
3                        46055               0                      0
4                        24450               1                 197000
5                        29991               0                      0
6                        20495               1                 118000
7                         9152               1                  65000
8                        28489               1                  56000
9                         3244               1                  17000
10                        7123               0                      0
11                       45223               1                  26000
12                       64798               1                  72000
13                       26679               1                  44000
14                        8458               1                 150000
15                        2039               1                  80000
16                       79957               1                  24000
17                       21714               0                      0
18                       14863               1                  44000
19                        3218               0                      0
20                       28631               1                  41000
21                       25550               1                  30000
22                        4482               1                  10000
23                       27468               0                      0
24                       79150               1                  94000
25                       32392               1                 129000
26                       21411               1                  92000
27                       19166               1                  83000
28                        5005               1                  39000
29                        2975               1                  16000
...                        ...             ...                    ...
3751                      3935               0                      0
3752                      6554               0                      0
3753                       708               0                      0
3754                     13626               0                      0
3755                      8097               0                      0
3756                      4611               0                      0
3757                      2868               1                    575
3758                     24082               0                      0
3759                      1006               0                      0
3760                      2259               1                  19000
3761                      5592               0                      0
3762                     41059               1                  25000
3763                      5963               1                    352
3764                     13693               0                      0
3765                      8094               0                      0
3766                      4293               0                      0
3767                      2787               0                      0
3768                      1810               0                      0
3769                     45696               1                   9000
3770                     13396               1                  14000
3771                      1500               0                      0
3772                     10691               0                      0
3773                       669               0                      0
3774                     52610               1                  56000
3775                      7014               0                      0
3776                     23456               1                  20000
3777                      3677               0                      0
3778                      3177               0                      0
3779                       427               1                  27000
3780                     54075               1                  40000

      facenumber_in_poster num_voted_users  num_user_for_reviews  imdb_score  \
0                        0          886204                  3054         7.9
1                        0          471220                  1238         7.1
2                        0         1144337                  2701         8.5
3                        0          383056                  1902         6.2
4                        0          371639                  3018         6.9
5                        0          240396                  2367         6.1
6                        0          548573                  2536         7.2
7                        0          354228                   802         7.5
8                        0          451803                  1225         7.0
9                        0          211765                   546         6.7
10                       0          316018                  2618         7.2
11                       0          793059                  2528         7.7
12                       0          272670                  1022         8.2
13                       0          202382                   751         5.9
14                       0          418214                  1290         7.0
15                       0          522030                  1498         7.8
16                       0          306320                   736         6.5
17                       0          383427                  1912         6.8
18                       0          235025                   265         7.3
19                       0          323207                  1439         6.0
20                       0          321227                  1067         6.7
21                       0          264183                   665         6.8
22                       0          101178                   283         6.3
23                       0          286095                   974         6.6
24                       0          278232                   657         7.2
25                       0          465019                   995         7.0
26                       0          395573                  1171         7.8
27                       0          381148                  1106         7.0
28                       0          273556                   428         7.2
29                       0          718837                  1043         8.4
...                    ...             ...                   ...         ...
3751                     9           18271                   150         4.4
3752                     9            6528                    32         6.1
3753                     9           12128                    61         5.6
3754                     9           12706                    75         5.3
3755                     9            7098                    41         5.0

In [61]:
print(imdb.columns)

Index(['movie_ID', 'movie_title', 'duration', 'color', 'title_year', 'country',
       'language', 'content_rating', 'budget_USD', 'gross_USD', 'net_USD',
       'profitable', 'director_name', 'director_top20?', 'director_facebook?',
       'director_facebook_likes', 'actor_1_name', 'actor_top20?',
       'actor_1_facebook?', 'actor_1_facebook_likes', 'actor_2_name',
       'actor_top20?.1', 'actor_2_facebook?', 'actor_2_facebook_likes',
       'actor_3_name', 'actor_top20?.2', 'actor_3_facebook?',
       'actor_3_facebook_likes', 'cast_total_facebook_likes',
       'movie_facebook?', 'movie_facebook_likes;', 'facenumber_in_poster',
       'num_voted_users', 'num_user_for_reviews', 'imdb_score',
       'imdb_top_250'],
      dtype='object')

In [62]:
imdb[["duration","gross_USD"]].describe()

          duration     gross_USD
count  3781.000000  3.781000e+03
mean    109.950278  5.182002e+07
std      22.299267  7.003776e+07
min      37.000000  1.620000e+02
25%      95.000000  7.605668e+06
50%     106.000000  2.896520e+07
75%     120.000000  6.600997e+07
max     325.000000  7.605058e+08

In [65]:
imdb["language"].value_counts().head(3)

English    3628
French       33
Spanish      23
Name: language, dtype: int64

In [66]:
imdb["imdb_score"]

0       7.9
1       7.1
2       8.5
3       6.2
4       6.9
5       6.1
6       7.2
7       7.5
8       7.0
9       6.7
10      7.2
11      7.7
12      8.2
13      5.9
14      7.0
15      7.8
16      6.5
17      6.8
18      7.3
19      6.0
20      6.7
21      6.8
22      6.3
23      6.6
24      7.2
25      7.0
26      7.8
27      7.0
28      7.2
29      8.4
       ...
3751    4.4
3752    6.1
3753    5.6
3754    5.3
3755    5.0
3756    7.5
3757    5.6
3758    5.5
3759    6.4
3760    6.1
3761    6.5
3762    4.3
3763    6.8
3764    6.4
3765    6.7
3766    2.3
3767    4.1
3768    3.4
3769    5.7
3770    5.7
3771    6.7
3772    5.7
3773    7.4
3774    6.1
3775    5.8
3776    5.7
3777    7.9
3778    5.0
3779    7.1
3780    7.7
Name: imdb_score, Length: 3781, dtype: float64

In [68]:
import numpy as np

In [71]:
imdb['score_group']=np.where(imdb['imdb_score']>7.5,'high','low')

In [73]:
imdb

,movie_ID,movie_title,duration,color,title_year,country,language,content_rating,budget_USD,gross_USD,...,actor_3_facebook_likes,cast_total_facebook_likes,movie_facebook?,movie_facebook_likes;,facenumber_in_poster,num_voted_users,num_user_for_reviews,imdb_score,imdb_top_250,score_group
0,1,Avatar,178,1,2009,USA,English,PG-13,237000000,760505847,...,855,4834,1,33000,0,886204,3054,7.9,0,high
1,2,Pirates of the Caribbean: At World's End,169,1,2007,USA,English,PG-13,300000000,309404152,...,1000,48350,0,0,0,471220,1238,7.1,0,low
2,3,The Dark Knight Rises,164,1,2012,USA,English,PG-13,250000000,448130642,...,23000,106759,1,164000,0,1144337,2701,8.5,1,high
3,4,Spider-Man 3,156,1,2007,USA,English,PG-13,258000000,336530303,...,4000,46055,0,0,0,383056,1902,6.2,0,low
4,5,Batman v Superman: Dawn of Justice,183,1,2016,USA,English,PG-13,250000000,330249062,...,2000,24450,1,197000,0,371639,3018,6.9,0,low
5,6,Superman Returns,169,1,2006,USA,English,PG-13,209000000,200069408,...,903,29991,0,0,0,240396,2367,6.1,0,low
6,7,Man of Steel,143,1,2013,USA,English,PG-13,225000000,291021565,...,748,20495,1,118000,0,548573,2536,7.2,0,low
7,8,The Hobbit: The Battle of the Five Armies,164,1,2014,New Zealand,English,PG-13,250000000,255108370,...,773,9152,1,65000,0,354228,802,7.5,0,low
8,9,The Amazing Spider-Man,153,1,2012,USA,English,PG-13,230000000,262030663,...,963,28489,1,56000,0,451803,1225,7.0,0,low
9,10,Robin Hood,156,1,2010,USA,English,PG-13,200000000,105219735,...,738,3244,1,17000,0,211765,546,6.7,0,low
10,11,King Kong,201,1,2005,New Zealand,English,PG-13,207000000,218051260,...,84,7123,0,0,0,316018,2618,7.2,0,low
11,12,Titanic,194,1,1997,USA,English,PG-13,200000000,658672302,...,794,45223,1,26000,0,793059,2528,7.7,0,high
12,13,Captain America: Civil War,147,1,2016,USA,English,PG-13,250000000,407197282,...,11000,64798,1,72000,0,272670,1022,8.2,1,high
13,14,Battleship,131,1,2012,USA,English,PG-13,209000000,65173160,...,627,26679,1,44000,0,202382,751,5.9,0,low
14,15,Jurassic World,124,1,2015,USA,English,PG-13,150000000,652177271,...,1000,8458,1,150000,0,418214,1290,7.0,0,low
15,16,Skyfall,143,1,2012,UK,English,PG-13,200000000,304360277,...,393,2039,1,80000,0,522030,1498,7.8,0,high
16,17,Alice in Wonderland,108,1,2010,USA,English,PG,200000000,334185206,...,11000,79957,1,24000,0,306320,736,6.5,0,low
17,18,X-Men: The Last Stand,104,1,2006,Canada,English,PG-13,210000000,234360014,...,560,21714,0,0,0,383427,1912,6.8,0,low
18,19,Monsters University,104,1,2013,USA,English,G,200000000,268488329,...,760,14863,1,44000,0,235025,265,7.3,0,low
19,20,Transformers: Revenge of the Fallen,150,1,2009,USA,English,PG-13,200000000,402076689,...,464,3218,0,0,0,323207,1439,6.0,0,low
20,21,The Amazing Spider-Man 2,142,1,2014,USA,English,PG-13,200000000,202853933,...,825,28631,1,41000,0,321227,1067,6.7,0,low
21,22,TRON: Legacy,125,1,2010,USA,English,PG,170000000,172051787,...,1000,25550,1,30000,0,264183,665,6.8,0,low
22,23,Cars 2,106,1,2011,USA,English,G,200000000,191450875,...,776,4482,1,10000,0,101178,283,6.3,0,low
23,24,Terminator Salvation,118,1,2009,USA,English,PG-13,200000000,125320003,...,988,27468,0,0,0,286095,974,6.6,0,low
24,25,Furious 7,140,1,2015,USA,English,PG-13,190000000,350034110,...,14000,79150,1,94000,0,278232,657,7.2,0,low
25,26,World War Z,123,1,2013,USA,English,PG-13,190000000,202351611,...,1000,32392,1,129000,0,465019,995,7.0,0,low
26,27,Star Trek Into Darkness,132,1,2013,USA,English,PG-13,190000000,228756232,...,928,21411,1,92000,0,395573,1171,7.8,0,high
27,28,Pacific Rim,131,1,2013,USA,English,PG-13,190000000,101785482,...,919,19166,1,83000,0,381148,1106,7.0,0,low
28,29,Brave,93,1,2012,USA,English,PG,185000000,237282182,...,838,5005,1,39000,0,273556,428,7.2,0,low
29,30,WALL-E,98,1,2008,USA,English,G,180000000,223806889,...,522,2975,1,16000,0,718837,1043,8.4,1,high
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3751,3752,Soul Plane,92,1,2004,USA,English,R,16000000,13922211,...,618,3935,0,0,9,18271,150,4.4,0,low
3752,3753,This Christmas,117,1,2007,USA,English,PG-13,13000000,49121934,...,912,6554,0,0,9,6528,32,6.1,0,low
3753,3754,5 Days of War,113,1,2011,Georgia,English,R,20000000,17149,...,18,708,0,0,9,12128,61,5.6,0,low
3754,3755,Sleepover,89,1,2004,USA,English,PG,10000000,8070311,...,2000,13626,0,0,9,12706,75,5.3,0,low
3755,3756,Baggage Claim,96,1,2013,USA,English,PG-13,8500000,21564616,...,1000,8097,0,0,9,7098,41,5.0,0,low
3756,3757,Best in Show,90,1,2000,USA,English,PG-13,6000000,18621249,...,658,4611,0,0,9,45859,340,7.5,0,low
3757,3758,The Players Club,104,1,1998,USA,English,R,4500000,23031390,...,498,2868,1,575,9,4345,26,5.6,0,low
3758,3759,Little Fockers,98,1,2010,USA,English,PG-13,100000000,148383780,...,708,24082,0,0,10,85531,152,5.5,0,low
3759,3760,Delivery Man,105,1,2013,USA,English,PG-13,26000000,30659817,...,110,1006,0,0,10,59805,95,6.4,0,low
3760,3761,My Big Fat Greek Wedding 2,94,1,2016,USA,English,PG-13,18000000,59573085,...,261,2259,1,19000,10,13562,103,6.1,0,low
3761,3762,Top Five,102,1,2014,USA,English,R,12000000,25277561,...,555,5592,0,0,10,21672,93,6.5,0,low
3762,3763,Movie 43,94,1,2013,USA,English,R,6000000,8828771,...,3000,41059,1,25000,10,79146,352,4.3,0,low
3763,3764,Get on the Bus,120,1,1996,USA,English,R,2400000,5731103,...,702,5963,1,352,10,4100,35,6.8,0,low
3764,3765,The Longest Yard,113,1,2005,USA,English,PG-13,82000000,158115031,...,421,13693,0,0,11,130070,316,6.4,0,low
3765,3766,I Heart Huckabees,107,1,2004,USA,English,R,22000000,12784713,...,678,8094,0,0,11,56813,381,6.7,0,low
3766,3767,Epic Movie,93,1,2007,USA,English,PG-13,20000000,39737645,...,729,4293,0,0,11,89687,666,2.3,0,low
3767,3768,One Direction: This Is Us,106,1,2013,USA,English,PG,10000000,28873374,...,547,2787,0,0,11,22161,68,4.1,0,low
3768,3769,God's Not Dead 2,120,1,2016,USA,English,PG,5000000,20773070,...,295,1810,0,0,11,4501,102,3.4,0,low
3769,3770,Valentine's Day,125,1,2010,USA,English,PG-13,52000000,110476776,...,11000,45696,1,9000,12,95437,211,5.7,0,low
3770,3771,What to Expect When You're Expecting,110,1,2012,USA,English,PG-13,40000000,41102171,...,651,13396,1,14000,12,57266,89,5.7,0,low
3771,3772,Taking Woodstock,120,1,2009,USA,English,R,30000000,7443007,...,210,1500,0,0,12,24663,71,6.7,0,low
3772,3773,Love the Coopers,107,1,2015,USA,English,PG-13,17000000,26284475,...,85,10691,0,0,13,9051,68,5.7,0,low
3773,3774,A Bridge Too Far,175,0,1977,USA,English,PG,26000000,50800000,...,14,669,0,0,14,40277,210,7.4,0,low
3774,3775,The Expendables 3,131,1,2014,USA,English,PG-13,90000000,39292022,...,11000,52610,1,56000,15,127258,351,6.1,0,low
3775,3776,Cheaper by the Dozen,94,1,2003,USA,English,PG,40000000,138614544,...,597,7014,0,0,15,75152,288,5.8,0,low
3776,3777,New Year's Eve,113,1,2011,USA,English,PG-13,56000000,54540525,...,307,23456,1,20000,15,66579,134,5.7,0,low
3777,3778,Boogie Nights,155,1,1997,USA,English,R,15000000,26384919,...,170,3677,0,0,15,189032,560,7.9,0,high
3778,3779,Battle of the Year,110,1,2013,USA,English,PG-13,20000000,8888355,...,826,3177,0,0,19,7894,25,5.0,0,low
3779,3780,The Master,144,1,2012,USA,English,R,32000000,16377274,...,15,427,1,27000,31,105144,405,7.1,0,low
3780,3781,500 Days of Summer,95,1,2009,USA,English,PG-13,7500000,32391374,...,11000,54075,1,40000,43,376600,494,7.7,0,high